version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - run: npm ci
      - run: 'npm run build:ng-zipkin'
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
            - "dist"
  test:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: xvfb-run -a npm run test -- --single-run --no-progress --browser=ChromeNoSandbox
workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
